### ISSUE TITLE
Plugin missing in GUI

### ISSUE THREAD

**Issue by remydev** [Antergos/nodebb-plugin-sso-auth0#10] opened 2017-12-07 08:51 UTC
I understand this plugin in a GUI SSO configuration (i like that ;)

But i have nothing in my GUI

![image](https://user-images.githubusercontent.com/10176486/33706270-de03ca4c-db33-11e7-971e-4bb7d9e81e56.png)

But is looks installed 
![image](https://user-images.githubusercontent.com/10176486/33706316-05fdd5ba-db34-11e7-9106-51707c978d66.png)

Something wrong ?

Thanks

**Comment by remydev** [comment] 2017-12-15 12:06
I thinks this is the plugin i want but i don't know if it's works.

**Comment by lots0logs** [comment] 2017-12-15 20:55
The plugin hasn't been tested with the latest version of NodeBB. Its possible that there is a compatibility issue there. I'll look into it as soon as I have time.

**Comment by remydev** [comment] 2017-12-16 14:20
Très bien merci,
J'ai testé build, restart .. rien a faire, je n'ai pas la GUI
Je ne connais pas le nodejs, donc je ne vais pas pouvoir aider, mais merci

**Comment by rwindegger** [comment] 2018-01-04 18:26
I've added a PR to fix one of the issues I've encountered. Besides that my current test environment looks good.

**Comment by lots0logs** [comment] 2018-01-06 06:11
Closing this as I cannot reproduce it. Something to note is that the plugin requires Node 7 or later.

**Closed as completed by lots0logs** 2018-01-06 06:11 UTC
Labels: bug, help welcomed
